### PR TITLE
Add unit test for scan command

### PR DESCRIPTION
**Pull request by mkretz**
Added some rudimentary tests for the scan command, mocking away the file io.

### CODE REVIEW

**Comment by mkretz** [comment]
run the test using `go test ./scan`

**Comment by bygui86** [comment]
Hi this, I had no time yet to review this.
I started this morning but I don't understand some different things and choices, so I will take a couple of minutes more to be sure to have a proper look.

**Comment by mkretz** [comment]
Hi @bygui86, I am going to go ahead and merge this PR because I want to continue working on the unit tests. I suggest that we do a review of all of the test code when I am done.

**Comment by bygui86** [comment]
Hi @mkretz thanks you for taking care of it.
This period is really busy for me. I'm not able to follow PRs and development of the project for now.
Can I still be included for a while? I really would like to continue contributing, but for now I have to think about my wedding and my new job.

**Comment by mkretz** [comment]
> Can I still be included for a while? I really would like to continue contributing, but for now I have to think about my wedding and my new job.

Sure thing, will keep you in the loop! Thanks for your contributions so far! Those are indeed important topics :-)! Congrats on both!

**Pull request merged**
